### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by limisc** [almunnings/drupal-vite-bootstrap#6]
The website encountered an unexpected error. Try again later.

InvalidArgumentException: Class "Drupal\dvb\Vite\ViteLibrary" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).
Drupal::classResolver('Drupal\dvb\Vite\ViteLibrary') (Line: 22)
dvb_library_info_alter(Array, 'dvb', NULL) (Line: 458)
Drupal\Core\Theme\ThemeManager->alterForTheme(Object, 'library_info', Array, 'dvb', NULL) (Line: 467)
Drupal\Core\Theme\ThemeManager->alter('library_info', Array, 'dvb') (Line: 379)
Drupal\Core\Asset\LibraryDiscoveryParser->parseLibraryInfo('dvb', 'themes/custom/drupal-vite-bootstrap') (Line: 130)
Drupal\Core\Asset\LibraryDiscoveryParser->buildByExtension('dvb') (Line: 87)
Drupal\Core\Asset\LibraryDiscoveryCollector->getLibraryDefinitions('dvb') (Line: 66)
Drupal\Core\Asset\LibraryDiscoveryCollector->resolveCacheMiss('dvb') (Line: 149)
Drupal\Core\Cache\CacheCollector->get('dvb') (Line: 44)
Drupal\Core\Asset\LibraryDiscovery->getLibrariesByExtension('dvb') (Line: 58)
Drupal\Core\Asset\LibraryDiscovery->getLibraryByName('dvb', 'hmr') (Line: 68)
Drupal\Core\Asset\LibraryDependencyResolver->doGetDependencies(Array) (Line: 41)
Drupal\Core\Asset\LibraryDependencyResolver->getLibrariesWithDependencies(Array) (Line: 87)
Drupal\Core\Asset\LibraryDependencyResolver->getMinimalRepresentativeSubset(Array) (Line: 113)
Drupal\Core\Asset\AssetResolver->getLibrariesToLoad(Object) (Line: 131)
Drupal\Core\Asset\AssetResolver->getCssAssets(Object, , Object) (Line: 321)
Drupal\Core\Render\HtmlResponseAttachmentsProcessor->processAssetLibraries(Object, Array) (Line: 165)
Drupal\Core\Render\HtmlResponseAttachmentsProcessor->processAttachments(Object) (Line: 97)
Drupal\big_pipe\Render\BigPipeResponseAttachmentsProcessor->processAttachments(Object) (Line: 45)
Drupal\Core\EventSubscriber\HtmlResponseSubscriber->onRespond(Object, 'kernel.response', Object)
call_user_func(Array, Object, 'kernel.response', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.response') (Line: 214)
Symfony\Component\HttpKernel\HttpKernel->filterResponse(Object, Object, 1) (Line: 202)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by almunnings** [comment]
Oh weird. 
In a new install?

Does clearing Drupal cache fit it?

**Comment by almunnings** [comment]
I wonder if this is related to this issue:

https://www.drupal.org/project/drupal/issues/3342669

Try restarting your docker/server?

**Comment by almunnings** [comment]
Ahhhhh, I'm pretty sure it was the folder-name, `VIte` should be `Vite`

**Comment by almunnings** [comment]
Reproduced & closed with 1bdf7fdee2a5e198e4f37d2ac6e7046e16ae18c5 -> 6ade7ce2dfa0d23799d018ee6c6bcf5e9eb0328e

Case sensitive file systems picked up the issue!
Cheers

**Comment by limisc** [comment]
newly cloned, and `npm ci`, `npm run dev`

got this error this time

The website encountered an unexpected error. Try again later.

TypeError: Drupal\dvb\Vite\ViteManifest::decode(): Return value must be of type array, null returned in Drupal\dvb\Vite\ViteManifest->decode() (line 54 of themes/custom/drupal-vite-bootstrap/src/Vite/ViteManifest.php).
Drupal\dvb\Vite\ViteManifest->find('assets/js/app.js', ) (Line: 65)
Drupal\dvb\Vite\ViteAsset->find('assets/js/app.js') (Line: 89)
Drupal\dvb\Vite\ViteLibrary->map(Array) (Line: 68)
Drupal\dvb\Vite\ViteLibrary->Drupal\dvb\Vite\{closure}(Array)
array_map(Object, Array) (Line: 68)
Drupal\dvb\Vite\ViteLibrary->alter(Array) (Line: 29)
dvb_library_info_alter(Array, 'dvb', NULL) (Line: 458)
Drupal\Core\Theme\ThemeManager->alterForTheme(Object, 'library_info', Array, 'dvb', NULL) (Line: 467)
Drupal\Core\Theme\ThemeManager->alter('library_info', Array, 'dvb') (Line: 379)
Drupal\Core\Asset\LibraryDiscoveryParser->parseLibraryInfo('dvb', 'themes/custom/drupal-vite-bootstrap') (Line: 130)
Drupal\Core\Asset\LibraryDiscoveryParser->buildByExtension('dvb') (Line: 87)
Drupal\Core\Asset\LibraryDiscoveryCollector->getLibraryDefinitions('dvb') (Line: 66)
Drupal\Core\Asset\LibraryDiscoveryCollector->resolveCacheMiss('dvb') (Line: 149)
Drupal\Core\Cache\CacheCollector->get('dvb') (Line: 44)
Drupal\Core\Asset\LibraryDiscovery->getLibrariesByExtension('dvb') (Line: 58)
Drupal\Core\Asset\LibraryDiscovery->getLibraryByName('dvb', 'hmr') (Line: 68)
Drupal\Core\Asset\LibraryDependencyResolver->doGetDependencies(Array) (Line: 41)
Drupal\Core\Asset\LibraryDependencyResolver->getLibrariesWithDependencies(Array) (Line: 87)
Drupal\Core\Asset\LibraryDependencyResolver->getMinimalRepresentativeSubset(Array) (Line: 113)
Drupal\Core\Asset\AssetResolver->getLibrariesToLoad(Object) (Line: 131)
Drupal\Core\Asset\AssetResolver->getCssAssets(Object, , Object) (Line: 321)
Drupal\Core\Render\HtmlResponseAttachmentsProcessor->processAssetLibraries(Object, Array) (Line: 165)
Drupal\Core\Render\HtmlResponseAttachmentsProcessor->processAttachments(Object) (Line: 97)
Drupal\big_pipe\Render\BigPipeResponseAttachmentsProcessor->processAttachments(Object) (Line: 45)
Drupal\Core\EventSubscriber\HtmlResponseSubscriber->onRespond(Object, 'kernel.response', Object)
call_user_func(Array, Object, 'kernel.response', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.response') (Line: 214)
Symfony\Component\HttpKernel\HttpKernel->filterResponse(Object, Object, 1) (Line: 202)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by almunnings** [comment]
Can reproduce with incorrect paths

`/admin/appearance/settings/dvb`

Can you double check your settings here.

Port: `3000`
Vite dist path: `dist`
Manifest path: `dist/.vite/manifest.json`

Will probably fix it up for you.

**Comment by limisc** [comment]
Thanks, it works 
Cheers
