### ISSUE TITLE
Problem ddev

### ISSUE THREAD

**Issue by arieleanarion** [almunnings/drupal-vite-bootstrap#7]
Thank you for theme
All done as described. 
ddev npm run dev is running on terminal successfully, but localhost:3000 in browser shows 404 page not found

**Comment by almunnings** [comment]
https://github.com/almunnings/drupal-vite-bootstrap/assets/1531329/9bac7441-f5cc-46c2-9e24-1bd1e3a476ab

Did you enable `Developer Mode` in the Theme settings?

You don't need to access Vite on the server address. Drupal will hook it up for you.
